# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('new_book', models.IntegerField(max_length=999999)),
                ('used_book', models.IntegerField(max_length=999999)),
                ('rental_book', models.IntegerField(max_length=999999)),
                ('ebook', models.IntegerField(max_length=999998)),
                ('new_book_price', models.IntegerField(max_length=999)),
                ('used_book_price', models.IntegerField(max_length=999)),
                ('rental_book_price', models.IntegerField(max_length=999)),
                ('ebook_price', models.IntegerField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('profesor', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('section', models.IntegerField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Book')),
            ],
        ),
    ]
