# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ebook',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='ebook_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='new_book',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='new_book_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='rental_book',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='rental_book_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='used_book',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='used_book_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.IntegerField(),
        ),
    ]
