# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20161120_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=999999),
        ),
        migrations.AlterField(
            model_name='book',
            name='ebook',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='ebook_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='new_book',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='new_book_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='rental_book',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='rental_book_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='used_book',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='used_book_price',
            field=models.FloatField(),
        ),
    ]
