# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20161124_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ebook',
            new_name='ebook_quantity',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='new_book',
            new_name='new_book_quantity',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='rental_book',
            new_name='rental_book_quantity',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='used_book',
            new_name='used_book_quantity',
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
